# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: siimply tech
description: > # this means to ignore newlines until "baseurl:"
  a blog built & maintainined by tech enthusiasts, providing high-quality content to the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://siimplytech.com" # the base hostname & protocol for your site
enforce_ssl: siimplytech.com


# Build settings
markdowm: kramdown

kramdown:
  input:      GFM
  auto_ids:   false

exclude: ["README.md", "LICENSE.md", "screenshot.png"]
